apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prueba-devsecops
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/andresfcr01/Prueba-DevSecOps.git
    targetRevision: HEAD
    path: helm 
  
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true